/**
 * generated by Xtext 2.16.0
 */
package com.dexels.navajo.dsl.rr.validation;

import com.dexels.navajo.dsl.rr.validation.AbstractReactiveValidator;

/**
 * This class contains custom validation rules.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
@SuppressWarnings("all")
public class ReactiveValidator extends AbstractReactiveValidator {
}
