/*
 * generated by Xtext 2.16.0
 */
package com.dexels.navajo.dsl.rr.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractReactiveScopeProvider extends DelegatingScopeProvider {
}
