/**
 * generated by Xtext 2.16.0
 */
package com.dexels.navajo.dsl.expression;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Exists Tml Reference</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see com.dexels.navajo.dsl.expression.ExpressionPackage#getExistsTmlReference()
 * @model
 * @generated
 */
public interface ExistsTmlReference extends TmlReference
{
} // ExistsTmlReference
