/**
 * generated by Xtext 2.16.0
 */
package com.dexels.navajo.dsl.expression;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Path Sequence</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link com.dexels.navajo.dsl.expression.PathSequence#getPathElements <em>Path Elements</em>}</li>
 * </ul>
 *
 * @see com.dexels.navajo.dsl.expression.ExpressionPackage#getPathSequence()
 * @model
 * @generated
 */
public interface PathSequence extends EObject
{
	/**
	 * Returns the value of the '<em><b>Path Elements</b></em>' attribute list.
	 * The list contents are of type {@link java.lang.String}.
	 * <!-- begin-user-doc -->
	 * <p>
	 * If the meaning of the '<em>Path Elements</em>' attribute list isn't clear,
	 * there really should be more of a description here...
	 * </p>
	 * <!-- end-user-doc -->
	 * @return the value of the '<em>Path Elements</em>' attribute list.
	 * @see com.dexels.navajo.dsl.expression.ExpressionPackage#getPathSequence_PathElements()
	 * @model
	 * @generated
	 */
	EList<String> getPathElements();

} // PathSequence
