/**
 * generated by Xtext 2.16.0
 */
package com.dexels.navajo.dsl.rr.reactive;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Greeting</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link com.dexels.navajo.dsl.rr.reactive.Greeting#getAap <em>Aap</em>}</li>
 * </ul>
 *
 * @see com.dexels.navajo.dsl.rr.reactive.ReactivePackage#getGreeting()
 * @model
 * @generated
 */
public interface Greeting extends EObject
{
  /**
   * Returns the value of the '<em><b>Aap</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Aap</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Aap</em>' attribute.
   * @see #setAap(String)
   * @see com.dexels.navajo.dsl.rr.reactive.ReactivePackage#getGreeting_Aap()
   * @model
   * @generated
   */
  String getAap();

  /**
   * Sets the value of the '{@link com.dexels.navajo.dsl.rr.reactive.Greeting#getAap <em>Aap</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Aap</em>' attribute.
   * @see #getAap()
   * @generated
   */
  void setAap(String value);

} // Greeting
