/**
 * generated by Xtext 2.16.0
 */
package com.dexels.navajo.dsl.rr.scoping;

import com.dexels.navajo.dsl.rr.scoping.AbstractReactiveScopeProvider;

/**
 * This class contains custom scoping description.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#scoping
 * on how and when to use it.
 */
@SuppressWarnings("all")
public class ReactiveScopeProvider extends AbstractReactiveScopeProvider {
}
