/*
 * generated by Xtext 2.16.0
 */
package com.dexels.navajo.dsl.rr.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class ReactiveAntlrTokenFileProvider implements IAntlrTokenFileProvider {

	@Override
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
		return classLoader.getResourceAsStream("com/dexels/navajo/dsl/rr/parser/antlr/internal/InternalReactive.tokens");
	}
}
