/*
 * generated by Xtext 2.16.0
 */
package com.dexels.navajo.dsl.rr.parser.antlr;

import com.dexels.navajo.dsl.rr.parser.antlr.internal.InternalReactiveParser;
import com.dexels.navajo.dsl.rr.services.ReactiveGrammarAccess;
import com.google.inject.Inject;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;

public class ReactiveParser extends AbstractAntlrParser {

	@Inject
	private ReactiveGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS");
	}
	

	@Override
	protected InternalReactiveParser createParser(XtextTokenStream stream) {
		return new InternalReactiveParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "Model";
	}

	public ReactiveGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(ReactiveGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
