/**
 * generated by Xtext 2.16.0
 */
package com.dexels.navajo.dsl.rr.ide;

import com.dexels.navajo.dsl.rr.ide.AbstractReactiveIdeModule;

/**
 * Use this class to register ide components.
 */
@SuppressWarnings("all")
public class ReactiveIdeModule extends AbstractReactiveIdeModule {
}
