/**
 * generated by Xtext 2.16.0
 */
package com.dexels.navajo.dsl.rr;

import com.dexels.navajo.dsl.rr.ReactiveStandaloneSetupGenerated;

/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
@SuppressWarnings("all")
public class ReactiveStandaloneSetup extends ReactiveStandaloneSetupGenerated {
  public static void doSetup() {
    new ReactiveStandaloneSetup().createInjectorAndDoEMFRegistration();
  }
}
