/**
 * generated by Xtext 2.16.0
 */
package com.dexels.navajo.dsl.rr;

import com.dexels.navajo.dsl.rr.AbstractReactiveRuntimeModule;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
@SuppressWarnings("all")
public class ReactiveRuntimeModule extends AbstractReactiveRuntimeModule {
}
