/*
 * generated by Xtext 2.16.0
 */
package com.dexels.navajo.dsl.rr.validation;

import java.util.ArrayList;
import java.util.List;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.xtext.validation.AbstractDeclarativeValidator;

public abstract class AbstractReactiveValidator extends AbstractDeclarativeValidator {
	
	@Override
	protected List<EPackage> getEPackages() {
		List<EPackage> result = new ArrayList<EPackage>();
		result.add(com.dexels.navajo.dsl.rr.reactive.ReactivePackage.eINSTANCE);
		result.add(EPackage.Registry.INSTANCE.getEPackage("http://www.dexels.com/expression/1.0"));
		return result;
	}
}
