/**
 * generated by Xtext 2.16.0
 */
package com.dexels.navajo.dsl.expression.impl;

import com.dexels.navajo.dsl.expression.ExistsTmlReference;
import com.dexels.navajo.dsl.expression.ExpressionPackage;

import org.eclipse.emf.ecore.EClass;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Exists Tml Reference</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class ExistsTmlReferenceImpl extends TmlReferenceImpl implements ExistsTmlReference
{
	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ExistsTmlReferenceImpl()
	{
		super();
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	protected EClass eStaticClass()
	{
		return ExpressionPackage.Literals.EXISTS_TML_REFERENCE;
	}

} //ExistsTmlReferenceImpl
