/*
 * generated by Xtext 2.16.0
 */
package com.dexels.navajo.dsl.rr


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class ReactiveStandaloneSetup extends ReactiveStandaloneSetupGenerated {

	def static void doSetup() {
		new ReactiveStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
